[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
; These flags tell the compiler to use the S3's internal USB for Serial
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps = 
    knolleary/PubSubClient
    bblanchon/ArduinoJson
    adafruit/Adafruit NeoPixel
    adafruit/Adafruit MPU6050
    adafruit/Adafruit Unified Sensor